### ISSUE TITLE
Timeouts on PMD (waiting for PMD 7.0.0)

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#207]
We detected that on some analysis PMD is giving an TImeout stopping the tool from returning the analysis results.

An Example of the error we encountered was:

KubernetesDockerRunner: Container for codacy/codacy-pmd:3.0.0 exited with non-zero code 1
Sep 26, 2019 9:33:02 AM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.14.0/pmd_userdocs_incremental_analysis.html
Error executing the tool
java.lang.OutOfMemoryError: Java heap space
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1236)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parseFunctionBody(Parser.java:740)
	at org.mozilla.javascript.Parser.arrowFunction(Parser.java:986)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2267)
	at org.mozilla.javascript.Parser.argumentList(Parser.java:2598)
	at org.mozilla.javascript.Parser.memberExprTail(Parser.java:2748)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:2667)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2529)
	at org.mozilla.javascript.Parser.mulExpr(Parser.java:2454)
	at org.mozilla.javascript.Parser.addExpr(Parser.java:2438)
	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2419)
	at org.mozilla.javascript.Parser.relExpr(Parser.java:2394)
	at org.mozilla.javascript.Parser.eqExpr(Parser.java:2366)
	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2355)
	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2344)
	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2333)
	at org.mozilla.javascript.Parser.andExpr(Parser.java:2322)
	at org.mozilla.javascript.Parser.orExpr(Parser.java:2311)
	at org.mozilla.javascript.Parser.condExpr(Parser.java:2275)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2238)
	at org.mozilla.javascript.Parser.expr(Parser.java:2217)
	at org.mozilla.javascript.Parser.nameOrLabel(Parser.java:1970)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1229)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parseFunctionBody(Parser.java:740)
	at org.mozilla.javascript.Parser.arrowFunction(Parser.java:986)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2267)
	at org.mozilla.javascript.Parser.argumentList(Parser.java:2598)
	at org.mozilla.javascript.Parser.memberExprTail(Parser.java:2748)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:2667)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2529)

KubernetesDockerRunner: Container for codacy/codacy-pmd:3.0.0 exited with non-zero code 1
Sep 26, 2019 9:34:32 AM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.14.0/pmd_userdocs_incremental_analysis.html
Error executing the tool
java.lang.OutOfMemoryError: Java heap space
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1236)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parse(Parser.java:642)
	at org.mozilla.javascript.Parser.parse(Parser.java:577)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parseEcmascript(EcmascriptParser.java:56)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parse(EcmascriptParser.java:65)
	at net.sourceforge.pmd.lang.ecmascript.Ecmascript3Parser.parse(Ecmascript3Parser.java:41)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:111)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:175)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

KubernetesDockerRunner: Container for codacy/codacy-pmd:3.0.0 exited with non-zero code 1
Sep 26, 2019 9:33:41 AM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.14.0/pmd_userdocs_incremental_analysis.html
Error executing the tool
java.lang.OutOfMemoryError: Java heap space
	at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3068)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:2631)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2529)
	at org.mozilla.javascript.Parser.mulExpr(Parser.java:2454)
	at org.mozilla.javascript.Parser.addExpr(Parser.java:2438)
	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2419)
	at org.mozilla.javascript.Parser.relExpr(Parser.java:2394)
	at org.mozilla.javascript.Parser.eqExpr(Parser.java:2366)
	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2355)
	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2344)
	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2333)
	at org.mozilla.javascript.Parser.andExpr(Parser.java:2322)
	at org.mozilla.javascript.Parser.orExpr(Parser.java:2311)
	at org.mozilla.javascript.Parser.condExpr(Parser.java:2275)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2238)
	at org.mozilla.javascript.Parser.expr(Parser.java:2217)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1236)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parse(Parser.java:642)
	at org.mozilla.javascript.Parser.parse(Parser.java:577)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parseEcmascript(EcmascriptParser.java:56)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parse(EcmascriptParser.java:65)
	at net.sourceforge.pmd.lang.ecmascript.Ecmascript3Parser.parse(Ecmascript3Parser.java:41)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:111)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:175)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

KubernetesDockerRunner: Container for codacy/codacy-pmd:3.0.0 exited with non-zero code 1
Sep 26, 2019 9:31:16 AM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.14.0/pmd_userdocs_incremental_analysis.html
Error executing the tool
java.lang.OutOfMemoryError: Java heap space
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1236)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parse(Parser.java:642)
	at org.mozilla.javascript.Parser.parse(Parser.java:577)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parseEcmascript(EcmascriptParser.java:56)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parse(EcmascriptParser.java:65)
	at net.sourceforge.pmd.lang.ecmascript.Ecmascript3Parser.parse(Ecmascript3Parser.java:41)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:111)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:175)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

KubernetesDockerRunner: Container for codacy/codacy-pmd:3.0.0 exited with non-zero code 1
Sep 26, 2019 9:32:34 AM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.14.0/pmd_userdocs_incremental_analysis.html
Error executing the tool
java.lang.OutOfMemoryError: Java heap space
	at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3068)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:2631)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2529)
	at org.mozilla.javascript.Parser.mulExpr(Parser.java:2454)
	at org.mozilla.javascript.Parser.addExpr(Parser.java:2438)
	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2419)
	at org.mozilla.javascript.Parser.relExpr(Parser.java:2394)
	at org.mozilla.javascript.Parser.eqExpr(Parser.java:2366)
	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2355)
	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2344)
	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2333)
	at org.mozilla.javascript.Parser.andExpr(Parser.java:2322)
	at org.mozilla.javascript.Parser.orExpr(Parser.java:2311)
	at org.mozilla.javascript.Parser.condExpr(Parser.java:2275)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2238)
	at org.mozilla.javascript.Parser.expr(Parser.java:2217)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1236)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parse(Parser.java:642)
	at org.mozilla.javascript.Parser.parse(Parser.java:577)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parseEcmascript(EcmascriptParser.java:56)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parse(EcmascriptParser.java:65)
	at net.sourceforge.pmd.lang.ecmascript.Ecmascript3Parser.parse(Ecmascript3Parser.java:41)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:111)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:175)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

KubernetesDockerRunner: Container for codacy/codacy-pmd:3.0.0 exited with non-zero code 1
Sep 26, 2019 9:33:45 AM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.14.0/pmd_userdocs_incremental_analysis.html
Error executing the tool
java.lang.OutOfMemoryError: Java heap space
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1236)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parse(Parser.java:642)
	at org.mozilla.javascript.Parser.parse(Parser.java:577)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parseEcmascript(EcmascriptParser.java:56)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parse(EcmascriptParser.java:65)
	at net.sourceforge.pmd.lang.ecmascript.Ecmascript3Parser.parse(Ecmascript3Parser.java:41)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:111)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:175)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

KubernetesDockerRunner: Container for codacy/codacy-pmd:3.0.0 exited with non-zero code 1
Sep 26, 2019 9:34:57 AM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.14.0/pmd_userdocs_incremental_analysis.html
Error executing the tool
java.lang.OutOfMemoryError: Java heap space
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1236)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parse(Parser.java:642)
	at org.mozilla.javascript.Parser.parse(Parser.java:577)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parseEcmascript(EcmascriptParser.java:56)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parse(EcmascriptParser.java:65)
	at net.sourceforge.pmd.lang.ecmascript.Ecmascript3Parser.parse(Ecmascript3Parser.java:41)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:111)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:175)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Error on file packages/main/app/containers/Account/Authorize/Authorize.js:1. Cause: Failed to analyse file

KubernetesDockerRunner: Container for codacy/codacy-pmd:3.0.0 exited with non-zero code 1
Sep 26, 2019 9:34:26 AM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.14.0/pmd_userdocs_incremental_analysis.html
Error executing the tool
java.lang.OutOfMemoryError: Java heap space
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1236)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parse(Parser.java:642)
	at org.mozilla.javascript.Parser.parse(Parser.java:577)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parseEcmascript(EcmascriptParser.java:56)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parse(EcmascriptParser.java:65)
	at net.sourceforge.pmd.lang.ecmascript.Ecmascript3Parser.parse(Ecmascript3Parser.java:41)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:111)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:175)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

KubernetesDockerRunner: Container for codacy/codacy-pmd:3.0.0 exited with non-zero code 1
Sep 26, 2019 9:31:07 AM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.14.0/pmd_userdocs_incremental_analysis.html
Error executing the tool
java.lang.OutOfMemoryError: Java heap space
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1236)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parse(Parser.java:642)
	at org.mozilla.javascript.Parser.parse(Parser.java:577)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parseEcmascript(EcmascriptParser.java:56)
	at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParser.parse(EcmascriptParser.java:65)
	at net.sourceforge.pmd.lang.ecmascript.Ecmascript3Parser.parse(Ecmascript3Parser.java:41)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:111)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:175)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/7961'>Zendesk ticket #7961</a>)<br>gz#7961</i>

**Comment by mrfyda** [comment]
Reported as still happening.
Let's discuss what else we could do.

**Comment by lolgab** [comment]
This bug is from Rhino 1.7.7.2, a dependency of PMD.
It will be solved when PMD releases version 7.0.0 which drops support for Java 7 and bumps Rhino to 1.7.11 which solves this problem but drops Java 7 support too.

**Comment by mrfyda** [comment]
Closing for now

**Comment by paulacodacy** [comment]
Hi @lolgab @mrfyda, this issue still occurs and there hasn't been updates on https://github.com/pmd/pmd/issues/2081. What can we do in the meantime (while waiting for PMD v7.0.0 release) as a workaround?

**Comment by lolgab** [comment]
We can't do anything sadly.
