### ISSUE TITLE
Bandit analyses is failing

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#335]
Bandit analyses is failing with below error. This seems to be only happening in the UI, since when running in cli, the analyses is completed.
```

KubernetesDockerRunner: Container for codacy/codacy-bandit:1.2.1 exited with non-zero code 1
Error executing the tool
java.lang.Exception: Exit code: 2
stdout: List()
sterr: List()

	at codacy.bandit.Bandit$.runTool(Bandit.scala:111)
	at codacy.bandit.Bandit$.$anonfun$apply$1(Bandit.scala:37)
	at scala.util.Try$.apply(Try.scala:210)
	at codacy.bandit.Bandit$.apply(Bandit.scala:27)
	at com.codacy.tools.scala.seed.DockerEngine.executeTool(DockerEngine.scala:53)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:35)
	at scala.util.Success.map(Try.scala:262)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:27)
	at scala.util.Success.flatMap(Try.scala:258)
	at com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:26)
	at codacy.Engine.main(Engine.scala)<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9681'>Zendesk ticket #9681</a>)<br>gz#9681</i>
```

**Comment by franciscodua** [comment]
In version 1.6.0 bandit removed one of its patterns, B414, as you can check in their [change log](https://github.com/PyCQA/bandit/compare/1.5.1...1.6.0), or in the [commit](https://github.com/PyCQA/bandit/commit/823138f418905a99fb7bbff8bb35b97f6dc9e5ab).

For this reason, if you have the issue B414 anywhere in your configuration file, e.g., one of the skips, the tool will fail.

The project that resulted in this error, had the issue B414 in the skip list. Removing it should fix the problem.

Let us know if this fixed your problem.

**Comment by franciscodua** [comment]
I'll close this issue, but feel free to open it if you're still experiencing this problem after removing that specific pattern.
