### ISSUE TITLE
[CY-2400] Pattern “ESLint_JSON format” is delivered by ESlint even when not in the config file.

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#349]
In zendesk ticket: ".eslintrc.js" and "storefront.de-DE.json"

Description: ".eslintrc.js" doesn’t have rule "ESLint_JSON format" and this rule doesn’t belong to "stylelint-config-standard" (as expected since it's a stylelint plugin), but after re-analysing the project to have the latest results, tested json files like "storefront.de-DE.json" is still delivering unwanted "ESLint_JSON format" issues.  So, how “ESLint_JSON format” is triggered by ESLint?

I’ve also ran cli without  "extends: 'stylelint-config-standard'" to test the outcome, but it’s throwing:

```
stdout: 
stderr: Error: /src/.eslintrc.js:

 Environment key "es2020" is unknown
    at Object.keys.forEach.env (/usr/lib/node_modules/eslint/lib/config/config-validator.js:158:19)
    at Array.forEach (<anonymous>)
    at validateEnvironment (/usr/lib/node_modules/eslint/lib/config/config-validator.js:154:30)
    at Object.validate (/usr/lib/node_modules/eslint/lib/config/config-validator.js:263:5)
    at loadFromDisk (/usr/lib/node_modules/eslint/lib/config/config-file.js:544:19)
    at Object.load (/usr/lib/node_modules/eslint/lib/config/config-file.js:587:20)
    at Config.getLocalConfigHierarchy (/usr/lib/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/usr/lib/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/usr/lib/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/usr/lib/node_modules/eslint/lib/config.js:342:29)
 at codacy.eslint.ESLint$.$anonfun$apply$1(ESLint.scala:56)
 at scala.util.Try$.apply(Try.scala:213)
 at codacy.eslint.ESLint$.apply(ESLint.scala:25)
 at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)
 at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)
 at scala.util.Success.$anonfun$map$1(Try.scala:255)
 at scala.util.Success.map(Try.scala:213)
 at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)
 at scala.util.Success.flatMap(Try.scala:251)
 at com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)
 at codacy.Engine.main(Engine.scala)
 at com.codacy.plugins.runners.BinaryDockerRunner.$anonfun$run$4(BinaryDockerRunner.scala:90)
 at scala.util.Success.flatMap(Try.scala:251)
 at com.codacy.plugins.runners.BinaryDockerRunner.run(BinaryDockerRunner.scala:75)
 at com.codacy.plugins.results.traits.ToolRunner.$anonfun$apply$3(ToolRunner.scala:73)
 at scala.util.Success.flatMap(Try.scala:251)
 at com.codacy.plugins.results.traits.ToolRunner.$anonfun$apply$2(ToolRunner.scala:72)
at scala.util.Success.flatMap(Try.scala:251)
 at com.codacy.plugins.results.traits.ToolRunner.apply(ToolRunner.scala:60)
 at com.codacy.plugins.results.traits.ToolRunner.run(ToolRunner.scala:48)
 at com.codacy.analysis.core.tools.Tool.run(Tool.scala:82)
 at com.codacy.analysis.core.analysis.CodacyPluginsAnalyser.analyse(CodacyPluginsAnalyser.scala:23)
 at com.codacy.analysis.core.analysis.CodacyPluginsAnalyser.analyse(CodacyPluginsAnalyser.scala:14)
 at com.codacy.analysis.cli.analysis.AnalyseExecutor.$anonfun$issues$1(AnalyseExecutor.scala:111)
 at scala.util.Success.flatMap(Try.scala:251)
 at com.codacy.analysis.cli.analysis.AnalyseExecutor.issues(AnalyseExecutor.scala:105)
 at com.codacy.analysis.cli.analysis.AnalyseExecutor.$anonfun$run$5(AnalyseExecutor.scala:58)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
 at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
 at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
 at scala.collection.TraversableLike.map(TraversableLike.scala:238)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
 at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:51)
 at scala.collection.SetLike.map(SetLike.scala:104)
 at scala.collection.SetLike.map$(SetLike.scala:104)
 at scala.collection.AbstractSet.map(Set.scala:51)
 at scala.collection.parallel.ParIterableLike.map(ParIterableLike.scala:502)
 at scala.collection.parallel.ParIterableLike.map$(ParIterableLike.scala:500)
 at scala.collection.parallel.immutable.ParHashSet.map(ParHashSet.scala:50)
 at com.codacy.analysis.core.utils.SetOps$.mapInParallel(SetOps.scala:13)
 at com.codacy.analysis.cli.analysis.AnalyseExecutor.$anonfun$run$4(AnalyseExecutor.scala:51)
 at scala.util.Either.map(Either.scala:353)
 at com.codacy.analysis.cli.analysis.AnalyseExecutor.run(AnalyseExecutor.scala:49)
 at com.codacy.analysis.cli.command.AnalyseCommand.$anonfun$run$1(AnalyseCommand.scala:66)
 at scala.util.Either.flatMap(Either.scala:341)
 at com.codacy.analysis.cli.command.AnalyseCommand.run(AnalyseCommand.scala:65)
 at com.codacy.analysis.cli.MainImpl.runCommand(Main.scala:19)
 at com.codacy.analysis.cli.MainImpl.run(Main.scala:14)
 at com.codacy.analysis.cli.command.CLIApp.run(CLIApp.scala:22)
 at com.codacy.analysis.cli.command.CLIApp.run(CLIApp.scala:18)
 at com.codacy.analysis.cli.command.CommandAppWithBaseCommand.$anonfun$main$1(CommandAppWithBaseCommand.scala:103)
 at com.codacy.analysis.cli.command.CommandAppWithBaseCommand.$anonfun$main$1$adapted(CommandAppWithBaseCommand.scala:88)
at scala.Option.foreach(Option.scala:407)
at com.codacy.analysis.cli.command.CommandAppWithBaseCommand.main(CommandAppWithBaseCommand.scala:88)
 at com.codacy.analysis.cli.Main.main(Main.scala)
```
<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9953'>Zendesk ticket #9953</a>)<br>gz#9953</i>

**Comment by MDSLKTR** [comment]
Is this going to be tackled eventually?

**Comment by paulacodacy** [comment]
@codacy/toss Can you provide an estimate for when this can be tackled, please?

**Comment by franciscodua** [comment]
Hey
Probably, issues keep appearing, although not in the config file, because of the issue we opened [here](https://github.com/Bkucera/eslint-plugin-json-format/issues/14).

Following [these instructions](https://github.com/Bkucera/eslint-plugin-json-format#default-settings-eslintrc) you can probably ignore every file (*) and that way you shouldn't get new issues.

**Comment by franciscodua** [comment]
We decided to remove the plugin that outputted the `ESLint_JSON format` issue.
This decision was made because of several issues users had since we installed it.
I'll close this issue since it cannot happen anymore
