### ISSUE TITLE
Pattern "Quotes" from ESlint doesn't accept 2 options at same time

### ISSUE THREAD

**Issue by paulacodacy** [codacy/codacy-meta#405]
The Pattern "Quotes" in ESLint should be able to accept two options combined, for example: `"single", { "avoidEscape": true } ` in the parameter field, although this is giving the following tool error:

```
JSON :
KubernetesDockerRunner: Container for codacy/codacy-eslint:2.20.19 exited with non-zero code 1
Error: BaseConfig:
	Configuration for rule "quotes" is invalid:
	Value "\"single\", { \"avoidEscape\": true }" should be equal to one of the allowed values.

    at validateRuleOptions (/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at FileEnumerator._iterateFilesWithFile (/node_modules/eslint/lib/cli-engine/file-enumerator.js:320:43)
    at FileEnumerator._iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:301:25)
    at FileEnumerator.iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:59)

Javascript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:2.20.19 exited with non-zero code 1
Error: BaseConfig:
	Configuration for rule "quotes" is invalid:
	Value "\"single\", { \"avoidEscape\": true }" should be equal to one of the allowed values.

    at validateRuleOptions (/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at FileEnumerator._iterateFilesWithFile (/node_modules/eslint/lib/cli-engine/file-enumerator.js:320:43)
    at FileEnumerator._iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:301:25)
    at FileEnumerator.iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:59)
```

**Comment by lolgab** [comment]
The parameters were not added by the documentation generator because ESLint schema doesn't offer a default.
Adding the default manually solve this and the parameter will show up in the UI correctly:
Being tackled here: https://github.com/codacy/codacy-eslint/pull/487

**Comment by lolgab** [comment]
The Quotes rule parameters are now shown in the UI:
<img width="713" alt="Quotes parameters" src="https://user-images.githubusercontent.com/5793054/83501451-6a297780-a4c0-11ea-8eec-195149e32c4d.png">
