### ISSUE TITLE
[CY-2435] Support config stylelint-config-sass-guidelines

### ISSUE THREAD

**Issue by paulacodacy** [codacy/codacy-meta#408]
Currently, when stylelint config file have:
```
{
  "extends": "stylelint-config-sass-guidelines"
}
```

It'll give the following error:
```
KubernetesDockerRunner: Container for codacy/codacy-stylelint:2.5.26 exited with non-zero code 1
Error executing the tool
java.lang.Exception: Could not parse results json: Unrecognized token 'Error': was expecting ('true', 'false' or 'null')
 at [Source: (String)"Error: Could not find "stylelint-config-sass-guidelines". Do you need a `configBasedir`?
    at module.exports (/opt/docker/node_modules/stylelint/lib/utils/configurationError.js:10:14)
    at getModulePath (/opt/docker/node_modules/stylelint/lib/utils/getModulePath.js:27:9)
    at loadExtendedConfig (/opt/docker/node_modules/stylelint/lib/augmentConfig.js:191:21)
    at resultPromise.then (/opt/docker/node_modules/stylelint/lib/augmentConfig.js:168:11)"; line: 1, column: 6]

Json:
Error: Could not find "stylelint-config-sass-guidelines". Do you need a `configBasedir`?
    at module.exports (/opt/docker/node_modules/stylelint/lib/utils/configurationError.js:10:14)
    at getModulePath (/opt/docker/node_modules/stylelint/lib/utils/getModulePath.js:27:9)
    at loadExtendedConfig (/opt/docker/node_modules/stylelint/lib/augmentConfig.js:191:21)
    at resultPromise.then (/opt/docker/node_modules/stylelint/lib/augmentConfig.js:168:11)
              
	at codacy.stylelint.Stylelint$$anonfun$$nestedInanonfun$parseJson$1$1.applyOrElse(Stylelint.scala:92)
	at codacy.stylelint.Stylelint$$anonfun$$nestedInanonfun$parseJson$1$1.applyOrElse(Stylelint.scala:87)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recoverWith(Try.scala:236)
	at codacy.stylelint.Stylelint$.$anonfun$parseJson$1(Stylelint.scala:87)
	at scala.util.Success.flatMap(Try.scala:251)
	at codacy.stylelint.Stylelint$.parseJson(Stylelint.scala:85)
	at codacy.stylelint.Stylelint$.apply(Stylelint.scala:33)
	at com.codacy.tools.scala.seed.DockerEngine.executeTool(DockerEngine.scala:53)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:35)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:27)
	at scala.util.Success.flatMap(Try.scala:251)
	at com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:26)
	at codacy.Engine.main(Engine.scala)
```

See if we can support this:https://github.com/bjankord/stylelint-config-sass-guidelines

**Comment by franciscodua** [comment]
I'll close this issue since we're tracking it internally
