### ISSUE TITLE
[CY-2460] Support @vue/standard for ESLint

### ISSUE THREAD

**Issue by paulacodacy** [codacy/codacy-meta#409]
Currently the below in ".eslintrc.js" doesn't allow ESLint to complete its analysis.
` extends: ['@vue/standard']`

Give the Error:
```
KubernetesDockerRunner: Container for codacy/codacy-eslint:2.21.0 exited with non-zero code 1
Error: Failed to load config "@vue/standard" to extend from.
Referenced from: /src/.eslintrc.js
    at configMissingError (/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.loadInDirectory (/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46) {
  messageTemplate: 'extend-config-missing',
  messageData: { configName: '@vue/standard', importerName: '/src/.eslintrc.js' }
}

```

**Comment by franciscodua** [comment]
I'll close this issue since we're tracking it internally
