### ISSUE TITLE
ESlint failure using UI patterns and Graphql plugin

### ISSUE THREAD

**Issue by paulacodacy** [codacy/codacy-meta#418]
```
JSON :

KubernetesDockerRunner: Container for codacy/codacy-eslint:2.21.6 exited with non-zero code 1
Error: BaseConfig:
	Configuration for rule "graphql/required-fields" is invalid:
	Value [] should NOT have fewer than 1 items.

    at validateRuleOptions (/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at FileEnumerator._iterateFilesWithFile (/node_modules/eslint/lib/cli-engine/file-enumerator.js:320:43)
    at FileEnumerator._iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:301:25)
    at FileEnumerator.iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:59)

Javascript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:2.21.6 exited with non-zero code 1
Error: BaseConfig:
	Configuration for rule "graphql/required-fields" is invalid:
	Value [] should NOT have fewer than 1 items.

    at validateRuleOptions (/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at FileEnumerator._iterateFilesWithFile (/node_modules/eslint/lib/cli-engine/file-enumerator.js:320:43)
    at FileEnumerator._iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:301:25)
    at FileEnumerator.iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:59)

TypeScript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:2.21.6 exited with non-zero code 1
Error: BaseConfig:
	Configuration for rule "graphql/required-fields" is invalid:
	Value [] should NOT have fewer than 1 items.

    at validateRuleOptions (/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at FileEnumerator._iterateFilesWithFile (/node_modules/eslint/lib/cli-engine/file-enumerator.js:320:43)
    at FileEnumerator._iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:301:25)
    at FileEnumerator.iterateFiles (/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:59)
```<br><br><i>(related to <a href='https://codacy.zendesk.com/agent/tickets/10941'>Zendesk ticket #10941</a>)<br>gz#10941</i>

**Comment by lolgab** [comment]
The fix for is online. I'm closing this issue.
Feel free to re-open if you are still facing this problem.
