### ISSUE TITLE
Support @vue/prettier for ESLint

### ISSUE THREAD

**Issue by paulacodacy** [codacy/codacy-meta#421]
Currently the below in ".eslintrc.js" doesn't allow ESLint to complete its analysis. 
`extends: ['@vue/prettier']`

Gives the Error:
```
JSON :

KubernetesDockerRunner: Container for codacy/codacy-eslint:2.22.3 exited with non-zero code 1
Error: Failed to load config "@vue/prettier" to extend from.
Referenced from: /src/.eslintrc.js
    at configMissingError (/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.loadInDirectory (/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46) {
  messageTemplate: 'extend-config-missing',
  messageData: { configName: '@vue/prettier', importerName: '/src/.eslintrc.js' }
}

Javascript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:2.22.3 exited with non-zero code 1
Error: Failed to load config "@vue/prettier" to extend from.
Referenced from: /src/.eslintrc.js
    at configMissingError (/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.loadInDirectory (/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46) {
  messageTemplate: 'extend-config-missing',
  messageData: { configName: '@vue/prettier', importerName: '/src/.eslintrc.js' }
}

TypeScript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:2.22.3 exited with non-zero code 1
Error: Failed to load config "@vue/prettier" to extend from.
Referenced from: /src/.eslintrc.js
    at configMissingError (/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.loadInDirectory (/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46) {
  messageTemplate: 'extend-config-missing',
  messageData: { configName: '@vue/prettier', importerName: '/src/.eslintrc.js' }
}
```

**Comment by fjaeger** [comment]
I am very surprised that Codacy does not yet support Prettier in combination with ESLint as this seems to be a typical combination within the community: https://blog.theodo.com/2019/08/why-you-should-use-eslint-prettier-and-editorconfig-together/

I would really like to see the support being added to Codacy's ESLint toolchain, because otherwise it renders the service useless to our team and we would probably need to go back to manually running the linter within our CI/CD pipeline.

**Comment by lolgab** [comment]
Codacy does support the Prettier/ESLint combination. However, due to a infrastructural/security limitation, we can support only one version of every package.
Since Prettier/ESLint usually change the defaults between versions, it happens that you see false positives on Codacy if you have a different version installed.
Regarding the plugins in particular, for the same limitations we need to have all of them installed in out tool, this takes usually bunch of days for us to add them and put everything live.
We are currently working on a new addition to Codacy that lets you run your custom linters on CI and report issues to our API. When this will be implemented, you will be able to have a 1-1 relationship between what you have locally and what you have on Codacy.

**Comment by fjaeger** [comment]
> Codacy does support the Prettier/ESLint combination. However, due to a infrastructural/security limitation, we can support only one version of every package.
Since Prettier/ESLint usually change the defaults between versions, it happens that you see false positives on Codacy if you have a different version installed.

But currently, the whole ESLint process crashes for our projects and we do not see any false positives (which would be okay for now for us).

**Comment by lolgab** [comment]
> Maybe it would be possible to add this config?

Of course :-) It was already in out short-term TODO list.
We will close this issue when the config is available on codacy.com

**Comment by fjaeger** [comment]
Sounds great, but what does this mean in terms of timing? Will it take days, weeks or months? :)

**Comment by lolgab** [comment]
Most probably days :)

**Comment by lolgab** [comment]
Would you mind trying if `@vue/prettier` is enough for your project to work?
```bash
cd your-project-directory
docker run -v $PWD:/src codacy/codacy-eslint:3.1.0
```

**Comment by fjaeger** [comment]
I tried your suggested commands an I only get `Error reading /.codacyrc file` in the terminal. No further output, but it seems to run forever...

**Comment by lolgab** [comment]
Oh, probably is taking forever because it's trying to analyse the entire `node_modules` folder.
I'm sorry.
About `Error reading /.codacyrc file`, it's just a warning and it's not a problem.
The fact itself that it's not crashing, lets me think that it doesn't miss any dependency.
Maybe running on a fresh cloned repo without `node_modules` would terminate.

**Comment by fjaeger** [comment]
That's what I also thought, but even without the `node_modules` directory the process does not seem to terminate.

**Comment by lolgab** [comment]
The `@vue/prettier` config is now installed and available on Codacy.
I'm closing the issue. Feel free to reopen in case of problems.
