### ISSUE TITLE
[CY-2396] PMD fails when checking AndroidManifest.xml

### ISSUE THREAD

**Issue by paulacodacy** [codacy/codacy-meta#422]
User has his commits with PMD failing with the following error: 
`Error on file Mineware.Systems.OCR.Mobile/Mineware.Systems.OCR.Mobile.Android/Properties/AndroidManifest.xml:1. Cause: PMDException: Error while parsing /src/Mineware.Systems.OCR.Mobile/Mineware.Systems.OCR.Mobile.Android/Properties/AndroidManifest.xml`

The tool is using UI patterns and running the CLI locally, it didn't deliver errors.

More info on [in this internal ticket.](https://codacy.zendesk.com/agent/tickets/11019)<br><br><i>(related to <a href='https://codacy.zendesk.com/agent/tickets/11019'>Zendesk ticket #11019</a>)<br>gz#11019</i>

**Comment by josemiguelmelo** [comment]
It seems there are 2 distinct problems that are causing PMD to fail:

#### 1. **XML files failing to be parsed** 

PMD is failing to parse some XML file with the following exception:

```
Caused by: net.sourceforge.pmd.lang.ast.ParseException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at net.sourceforge.pmd.lang.xml.ast.XmlParser.parseDocument(XmlParser.java:59)
	at net.sourceforge.pmd.lang.xml.ast.XmlParser.parse(XmlParser.java:65)
	at net.sourceforge.pmd.lang.xml.XmlParser.parse(XmlParser.java:38)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:121)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:185)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:107)
	... 10 more
```

This exception is often caused by a white space before the XML declaration or a UTF-8 BOM (https://stackoverflow.com/questions/5138696/org-xml-sax-saxparseexception-content-is-not-allowed-in-prolog/7697281#7697281).

**To fix it**, you must ensure the encoding of those files is set to UTF-8 without BOM.

#### 2. **SQL files failing to be processed**

PMD is failing to analyse because the files have some characters ( `[` ) that are not supported by PMD PLSQL parser.

```
Caused by: net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error at line , column .  Encountered: "[" (91), after : "" (in lexical state 0)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParserTokenManager.getNextToken(PLSQLParserTokenManager.java:4899)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.jj_consume_token(PLSQLParser.java)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.SqlPlusCommand(PLSQLParser.java:419)
	at net.sourceforge.pmd.lang.plsql.ast.PLSQLParser.Input(PLSQLParser.java:162)
	at net.sourceforge.pmd.lang.plsql.PLSQLParser.parse(PLSQLParser.java:61)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:121)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:185)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:107)
```

As a workaround, you can:

- Disable all PLSQL related patterns for PMD
- Ignore the SQL files that contain those unsupported characters

If this does not solve the problem, please let us know.
