### ISSUE TITLE
ESLint config somehow inherits from airbnb and prettier

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#80]
<p>A customer is reporting: ESLint config not working properly</p>

<p>"Our Javascript developers us ESLint but their config somehow inherits from airbnb and prettier, below is our config, I'm told there have to be npm packages installed for this to work. How do we get this working?"</p>

<p>{<br/>
	"globals": </p>
{
		"cy": true,
		"Cypress": true,
		"enzyme": true,
		"expect": true,
		"sinon": true,
		"intlStub": true,
		"mountWithIntl": true
	}
<p>,<br/>
	"env": </p>
{
		"browser": true,
		"mocha": true
	}
<p>,<br/>
	"extends": <span class="error">&#91;&quot;airbnb&quot;, &quot;prettier&quot;&#93;</span>,<br/>
	"parser": "babel-eslint",<br/>
	"parserOptions": {<br/>
		"ecmaFeatures": </p>
{
			"experimentalObjectRestSpread": true
		}
<p>,<br/>
		"ecmaVersion": 8<br/>
	},<br/>
	"plugins": <span class="error">&#91;&quot;react&quot;, &quot;no-only-tests&quot;&#93;</span>,<br/>
	"rules": {<br/>
		"arrow-parens": 0,<br/>
		"comma-dangle": 0,<br/>
		"consistent-return": 0,<br/>
		"no-use-before-define": ["error", </p>
{
			"functions": false,
			"classes": true
		}
<p>],<br/>
		"no-plusplus": 0,<br/>
		"react/jsx-indent": 0,<br/>
		"react/no-did-update-set-state": 0,<br/>
		"react/no-unused-prop-types": 1,<br/>
		"react/prefer-stateless-function": 1,<br/>
		"react/require-default-props": 0,<br/>
		"space-before-function-paren": 0,<br/>
		"jsx-a11y/no-static-element-interactions": 1,<br/>
		"react/forbid-prop-types": 1,<br/>
		"global-require": 0,<br/>
		"no-underscore-dangle": 0,<br/>
		"import/prefer-default-export": 0,<br/>
		"no-only-tests/no-only-tests": 2<br/>
	},<br/>
	"settings": {<br/>
		"import/resolver": {<br/>
			"webpack": "webpack.config.js",<br/>
			"node": </p>
{
				"extensions": [".js", ".mjs"]
			}
<p>		}<br/>
	},<br/>
	"overrides": [{<br/>
		"files": <span class="error">&#91;&quot;*.spec.js&quot;&#93;</span>,<br/>
		"rules": </p>
{
			"prefer-arrow-callback": "off",
			"func-names": "off",
			"no-unused-expressions": "off",
			"no-mixed-operators": "off",
			"react/react-in-jsx-scope": "off",
			"react/jsx-filename-extension": "off",
			"import/no-extraneous-dependencies": "off"
		}
<p>	}]<br/>
}</p>

<p>Here is the log:</p>

<blockquote><p>JSON :</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>Docker exited with code 1</p></blockquote>
<blockquote><p>stdout:  </p></blockquote>
<blockquote><p>stderr: Error executing the tool</p></blockquote>
<blockquote><p>java.lang.Exception:  </p></blockquote>
<blockquote><p>codacy.eslint.ESLint$.parseToolResult(ESLint.scala:81)</p></blockquote>
<blockquote><p>codacy.eslint.ESLint$.$anonfun$apply$1(ESLint.scala:44)</p></blockquote>
<blockquote><p>scala.util.Try$.apply(Try.scala:209)</p></blockquote>
<blockquote><p>codacy.eslint.ESLint$.apply(ESLint.scala:25)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>scala.util.Success.$anonfun$map$1(Try.scala:251)</p></blockquote>
<blockquote><p>scala.util.Success.map(Try.scala:209)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>scala.util.Success.flatMap(Try.scala:247)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)</p></blockquote>
<blockquote><p>codacy.Engine.main(Engine.scala)</p></blockquote>
<blockquote><p>ESLint exited with code 2</p></blockquote>
<blockquote><p>message: Message: Premature end of file.</p></blockquote>
<blockquote><p>FileContents:</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>stdout:  </p></blockquote>
<blockquote><p>stderr: Error: /usr/lib/node_modules/eslint-config-airbnb/rules/react.js:</p></blockquote>
<blockquote><p>Configuration for rule "react/jsx-no-bind" is invalid:</p></blockquote>
<blockquote><p>Value {"ignoreRefs":true,"allowArrowFunctions":true,"allowFunctions":false,"allowBind":false,"ignoreDOMComponents":true} should NOT have additional properties.</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>Referenced from: /usr/lib/node_modules/eslint-config-airbnb/index.js</p></blockquote>
<blockquote><p>Referenced from: /src/.eslintrc</p></blockquote>
<blockquote><p>at validateRuleOptions (/usr/lib/node_modules/eslint/lib/config/config-validator.js:133:19)</p></blockquote>
<blockquote><p>at Object.keys.forEach.id <a href="http://object.keys.foreach.id/" class="external-link" rel="nofollow">http://object.keys.foreach.id/</a> (/usr/lib/node_modules/eslint/lib/config/config-validator.js:176:9)</p></blockquote>
<blockquote><p>at Array.forEach (<span class="error">&#91;anonymous&#93;</span>)</p></blockquote>
<blockquote><p>at validateRules (/usr/lib/node_modules/eslint/lib/config/config-validator.js:175:30)</p></blockquote>
<blockquote><p>at Object.validate (/usr/lib/node_modules/eslint/lib/config/config-validator.js:262:5)</p></blockquote>
<blockquote><p>at loadFromDisk (/usr/lib/node_modules/eslint/lib/config/config-file.js:521:19)</p></blockquote>
<blockquote><p>at load (/usr/lib/node_modules/eslint/lib/config/config-file.js:564:20)</p></blockquote>
<blockquote><p>at configExtends.reduceRight (/usr/lib/node_modules/eslint/lib/config/config-file.js:430:36)</p></blockquote>
<blockquote><p>at Array.reduceRight (<span class="error">&#91;anonymous&#93;</span>)</p></blockquote>
<blockquote><p>at applyExtends (/usr/lib/node_modules/eslint/lib/config/config-file.js:408:26)</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>at codacy.eslint.ESLint$.$anonfun$apply$1(ESLint.scala:55)</p></blockquote>
<blockquote><p>at scala.util.Try$.apply(Try.scala:209)</p></blockquote>
<blockquote><p>at codacy.eslint.ESLint$.apply(ESLint.scala:25)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>at scala.util.Success.$anonfun$map$1(Try.scala:251)</p></blockquote>
<blockquote><p>at scala.util.Success.map(Try.scala:209)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>at scala.util.Success.flatMap(Try.scala:247)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)</p></blockquote>
<blockquote><p>at codacy.Engine.main(Engine.scala)</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>Javascript :</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>Docker exited with code 1</p></blockquote>
<blockquote><p>stdout:  </p></blockquote>
<blockquote><p>stderr: Error executing the tool</p></blockquote>
<blockquote><p>java.lang.Exception:  </p></blockquote>
<blockquote><p>codacy.eslint.ESLint$.parseToolResult(ESLint.scala:81)</p></blockquote>
<blockquote><p>codacy.eslint.ESLint$.$anonfun$apply$1(ESLint.scala:44)</p></blockquote>
<blockquote><p>scala.util.Try$.apply(Try.scala:209)</p></blockquote>
<blockquote><p>codacy.eslint.ESLint$.apply(ESLint.scala:25)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>scala.util.Success.$anonfun$map$1(Try.scala:251)</p></blockquote>
<blockquote><p>scala.util.Success.map(Try.scala:209)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>scala.util.Success.flatMap(Try.scala:247)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)</p></blockquote>
<blockquote><p>codacy.Engine.main(Engine.scala)</p></blockquote>
<blockquote><p>ESLint exited with code 2</p></blockquote>
<blockquote><p>message: Message: Premature end of file.</p></blockquote>
<blockquote><p>FileContents:</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>stdout:  </p></blockquote>
<blockquote><p>stderr: Error: /usr/lib/node_modules/eslint-config-airbnb/rules/react.js:</p></blockquote>
<blockquote><p>Configuration for rule "react/jsx-no-bind" is invalid:</p></blockquote>
<blockquote><p>Value {"ignoreRefs":true,"allowArrowFunctions":true,"allowFunctions":false,"allowBind":false,"ignoreDOMComponents":true} should NOT have additional properties.</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>Referenced from: /usr/lib/node_modules/eslint-config-airbnb/index.js</p></blockquote>
<blockquote><p>Referenced from: /src/.eslintrc</p></blockquote>
<blockquote><p>at validateRuleOptions (/usr/lib/node_modules/eslint/lib/config/config-validator.js:133:19)</p></blockquote>
<blockquote><p>at Object.keys.forEach.id <a href="http://object.keys.foreach.id/" class="external-link" rel="nofollow">http://object.keys.foreach.id/</a> (/usr/lib/node_modules/eslint/lib/config/config-validator.js:176:9)</p></blockquote>
<blockquote><p>at Array.forEach (<span class="error">&#91;anonymous&#93;</span>)</p></blockquote>
<blockquote><p>at validateRules (/usr/lib/node_modules/eslint/lib/config/config-validator.js:175:30)</p></blockquote>
<blockquote><p>at Object.validate (/usr/lib/node_modules/eslint/lib/config/config-validator.js:262:5)</p></blockquote>
<blockquote><p>at loadFromDisk (/usr/lib/node_modules/eslint/lib/config/config-file.js:521:19)</p></blockquote>
<blockquote><p>at load (/usr/lib/node_modules/eslint/lib/config/config-file.js:564:20)</p></blockquote>
<blockquote><p>at configExtends.reduceRight (/usr/lib/node_modules/eslint/lib/config/config-file.js:430:36)</p></blockquote>
<blockquote><p>at Array.reduceRight (<span class="error">&#91;anonymous&#93;</span>)</p></blockquote>
<blockquote><p>at applyExtends (/usr/lib/node_modules/eslint/lib/config/config-file.js:408:26)</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>at codacy.eslint.ESLint$.$anonfun$apply$1(ESLint.scala:55)</p></blockquote>
<blockquote><p>at scala.util.Try$.apply(Try.scala:209)</p></blockquote>
<blockquote><p>at codacy.eslint.ESLint$.apply(ESLint.scala:25)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>at scala.util.Success.$anonfun$map$1(Try.scala:251)</p></blockquote>
<blockquote><p>at scala.util.Success.map(Try.scala:209)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>at scala.util.Success.flatMap(Try.scala:247)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)</p></blockquote>
<blockquote><p>at codacy.Engine.main(Engine.scala)</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>Docker exited with code 1</p></blockquote>
<blockquote><p>stdout:  </p></blockquote>
<blockquote><p>stderr: Error executing the tool</p></blockquote>
<blockquote><p>java.lang.Exception:  </p></blockquote>
<blockquote><p>codacy.eslint.ESLint$.parseToolResult(ESLint.scala:81)</p></blockquote>
<blockquote><p>codacy.eslint.ESLint$.$anonfun$apply$1(ESLint.scala:44)</p></blockquote>
<blockquote><p>scala.util.Try$.apply(Try.scala:209)</p></blockquote>
<blockquote><p>codacy.eslint.ESLint$.apply(ESLint.scala:25)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>scala.util.Success.$anonfun$map$1(Try.scala:251)</p></blockquote>
<blockquote><p>scala.util.Success.map(Try.scala:209)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>scala.util.Success.flatMap(Try.scala:247)</p></blockquote>
<blockquote><p>com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)</p></blockquote>
<blockquote><p>codacy.Engine.main(Engine.scala)</p></blockquote>
<blockquote><p>ESLint exited with code 2</p></blockquote>
<blockquote><p>message: Message: Premature end of file.</p></blockquote>
<blockquote><p>FileContents:</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>stdout:  </p></blockquote>
<blockquote><p>stderr: Error: /usr/lib/node_modules/eslint-config-airbnb/rules/react.js:</p></blockquote>
<blockquote><p>Configuration for rule "react/jsx-no-bind" is invalid:</p></blockquote>
<blockquote><p>Value {"ignoreRefs":true,"allowArrowFunctions":true,"allowFunctions":false,"allowBind":false,"ignoreDOMComponents":true} should NOT have additional properties.</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>Referenced from: /usr/lib/node_modules/eslint-config-airbnb/index.js</p></blockquote>
<blockquote><p>Referenced from: /src/iam_app/cypress/.eslintrc.json</p></blockquote>
<blockquote><p>at validateRuleOptions (/usr/lib/node_modules/eslint/lib/config/config-validator.js:133:19)</p></blockquote>
<blockquote><p>at Object.keys.forEach.id <a href="http://object.keys.foreach.id/" class="external-link" rel="nofollow">http://object.keys.foreach.id/</a> (/usr/lib/node_modules/eslint/lib/config/config-validator.js:176:9)</p></blockquote>
<blockquote><p>at Array.forEach (<span class="error">&#91;anonymous&#93;</span>)</p></blockquote>
<blockquote><p>at validateRules (/usr/lib/node_modules/eslint/lib/config/config-validator.js:175:30)</p></blockquote>
<blockquote><p>at Object.validate (/usr/lib/node_modules/eslint/lib/config/config-validator.js:262:5)</p></blockquote>
<blockquote><p>at loadFromDisk (/usr/lib/node_modules/eslint/lib/config/config-file.js:521:19)</p></blockquote>
<blockquote><p>at load (/usr/lib/node_modules/eslint/lib/config/config-file.js:564:20)</p></blockquote>
<blockquote><p>at configExtends.reduceRight (/usr/lib/node_modules/eslint/lib/config/config-file.js:430:36)</p></blockquote>
<blockquote><p>at Array.reduceRight (<span class="error">&#91;anonymous&#93;</span>)</p></blockquote>
<blockquote><p>at applyExtends (/usr/lib/node_modules/eslint/lib/config/config-file.js:408:26)</p></blockquote>
<blockquote><p></p></blockquote>
<blockquote><p>at codacy.eslint.ESLint$.$anonfun$apply$1(ESLint.scala:55)</p></blockquote>
<blockquote><p>at scala.util.Try$.apply(Try.scala:209)</p></blockquote>
<blockquote><p>at codacy.eslint.ESLint$.apply(ESLint.scala:25)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>at scala.util.Success.$anonfun$map$1(Try.scala:251)</p></blockquote>
<blockquote><p>at scala.util.Success.map(Try.scala:209)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)</p></blockquote>
<blockquote><p>at scala.util.Success.flatMap(Try.scala:247)</p></blockquote>
<blockquote><p>at com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)</p></blockquote>
<blockquote><p>at codacy.Engine.main(Engine.scala)</p></blockquote>

<p><sub>* Please see Zendesk Support tab for further comments and attachments.</sub></p>

**Comment by lolgab** [comment]
It should be solved with the new implementation.
